"""Dao protocol: the storage interface clients and services depend on."""

from typing import Protocol

from ..models.entities import (
    Campaign,
    Contact,
    Draft,
    Hospital,
    Send,
    Suppression,
)
from ..models.enums import ContactStatus, DraftStatus, InvocationStatus
from ..models.invocation import Invocation


class Dao(Protocol):
    def init_schema(self) -> None: ...
    def close(self) -> None: ...

    def upsert_hospital(self, hospital: Hospital) -> int: ...
    def get_hospital(self, hospital_id: int) -> Hospital | None: ...
    def find_hospitals(self, query: str = "", limit: int = 50) -> list[Hospital]: ...

    def save_contacts(self, contacts: list[Contact]) -> list[int]: ...
    def get_contact(self, contact_id: int) -> Contact | None: ...
    def find_contacts(
        self,
        status: ContactStatus | None = None,
        with_email_only: bool = True,
        scored_only: bool = False,
        limit: int = 100,
    ) -> list[Contact]: ...
    def update_contact_fit(
        self, contact_id: int, score: float, reasons: list[str], status: ContactStatus
    ) -> None: ...
    def set_contact_status(self, contact_id: int, status: ContactStatus) -> None: ...

    def upsert_campaign(self, campaign: Campaign) -> int: ...
    def get_campaign(self, name: str) -> Campaign | None: ...

    def save_draft(self, draft: Draft) -> int: ...
    def get_draft(self, draft_id: int) -> Draft | None: ...
    def find_drafts(self, status: DraftStatus | None = None, limit: int = 100) -> list[Draft]: ...
    def set_draft_status(self, draft_id: int, status: DraftStatus) -> None: ...
    def update_draft_body(
        self, draft_id: int, subject: str, body_text: str, body_html: str | None
    ) -> None: ...

    def record_send(self, send: Send) -> int: ...
    def sends_today(self) -> int: ...
    def sends_today_for_domain(self, domain: str) -> int: ...

    def is_suppressed(self, email: str) -> bool: ...
    def add_suppression(self, email: str, reason: str = "") -> None: ...
    def list_suppressions(self, limit: int = 200) -> list[Suppression]: ...

    def record_invocation(self, invocation: Invocation) -> None: ...
    def finish_invocation(
        self,
        invocation_id: str,
        status: InvocationStatus,
        output: dict | None = None,
        error: str | None = None,
    ) -> None: ...
    def find_invocations(self, limit: int = 20) -> list[Invocation]: ...
    def get_invocation(self, invocation_id: str) -> Invocation | None: ...

    def summary(self) -> dict: ...
