"""Operational limits. Safe local defaults; overridable via config/settings.yaml."""

DAILY_SEND_CAP = 50
PER_DOMAIN_CAP = 2

MIN_SEND_DELAY_SECONDS = 60
MAX_SEND_DELAY_SECONDS = 180

MIN_BODY_WORDS = 90
MAX_BODY_WORDS = 140
MAX_SUBJECT_CHARS = 60

FETCH_DELAY_SECONDS = 1.5
HTTP_TIMEOUT_SECONDS = 20.0
MAX_FETCH_PER_RUN = 200

MAX_HTML_TEXT_CHARS = 40000
LLM_MAX_TOKENS = 2048
LLM_TEMPERATURE = 0.4
